configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal
  matrix:

    # MSVC x86
    - arch:       win32
      bitsize:    x86
      platform:   x86
      qt:         5.9.2\msvc2015
      suffix:     msvc2015
      generator:  "Visual Studio 2015"
      PYTHON: "C:\\Python35"
      PLATFORM_: "x86"

    # MSVC x64
    - arch:       win32
      bitsize:    x64
      platform:   amd64
      qt:         5.9.2\msvc2015_64
      suffix:     msvc2015
      generator:  "Visual Studio 2015 Win64"
      PYTHON: "C:\\Python35"
      PLATFORM_: "amd64"

skip_commits:
  files:
    - '*.md'
    - docs/*
    - util/*

install:
  - set PYTHON3="%PYTHON%\python.exe"
  - set UseEnv=true
  - "%PYTHON3% -m pip freeze > requirements.txt"
  - "%PYTHON3% -m pip install -r requirements.txt"
  - "%PYTHON3% -m pip install setuptools"
  - "%PYTHON3% -m pip install virtualenvwrapper"
  - "%PYTHON3% -m pip install --upgrade google-api-python-client"
  - "%PYTHON3%  -V"
  - set QTDIR=C:\Qt\%qt%
  - set PATH=%PATH%;%QTDIR%;%QTDIR%\bin;C:\MinGW\bin

before_build:
  - qmake --version
  - md build
  - cd build
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM_%
  - qmake ..\ -tp vc -r "%APPVEYOR_BUILD_FOLDER%\pencil.pro" CONFIG+=GIT CONFIG+=NIGHTLY
  - echo %PLATFORM_%

build_script:
  - set BUILDTYPE=/t:Build
  - set SOLUTIONFILE32="%APPVEYOR_BUILD_FOLDER%\build\pencil.sln"
  - set SOLUTIONFILE64="%APPVEYOR_BUILD_FOLDER%\build\pencil.sln"
  - set BUILDTARGET32="/p:Configuration=Release,Platform=Win32"
  - set BUILDTARGET64="/p:Configuration=Release,Platform=x64"
  - if %PLATFORM_%==x86 call msbuild %SOLUTIONFILE32% %BUILDTYPE% %BUILDTARGET32%
  - if %PLATFORM_%==amd64     call msbuild %SOLUTIONFILE64% %BUILDTYPE% %BUILDTARGET64%

after_build:
  - set upload=no
  - if %APPVEYOR_REPO_BRANCH%==master set upload=yes
  - if "%FORCE_NIGHTLY_UPLOAD%"=="yes" set upload=yes
  - if %PLATFORM_%==x86 (
    echo "-----Deploying 32 Bit Version-----" &
    dir /s &
    md bin\plugins\ &
    echo "Copying ffmpeg plugin" &
    call curl.exe -o bin\plugins\ffmpeg-3.2.4-win32-static.zip "http://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.2.4-win32-static.zip" &
    call 7z.exe x bin\plugins\ffmpeg-3.2.4-win32-static.zip -o"bin\plugins" &
    echo "move ffmpeg.exe and delete ffmpeg leftovers" &
    del bin\plugins\ffmpeg-3.2.4-win32-static.zip &
    move bin\plugins\ffmpeg-3.2.4-win32-static\bin\ffmpeg.exe bin\plugins &
    rmdir /q /s bin\plugins\ffmpeg-3.2.4-win32-static &
    echo "copying qt libraries" &
    windeployqt bin\Pencil2D.exe &
    echo "zipping" &
    Rename bin Pencil2D &
    call 7z.exe a "pencil2d-win32-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" Pencil2D\ &
    echo "zipping done" &
    echo "what's inside?" &
    call 7z.exe l "pencil2d-win32-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    if %upload%==yes (
    echo "deploying to google drive" &
    cd %APPVEYOR_BUILD_FOLDER%\util &
    call %PYTHON%\\python.exe nightly-build-upload.py "%WIN32_NIGHTLY_PARENT%" "%APPVEYOR_BUILD_FOLDER%\build\pencil2d-win32-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    echo "32 Bit deployed" ) )

  - if %PLATFORM_%==amd64 (
    echo "----- Deploying 64 Bit Version -----" &
    echo "rename and zip folder" &
    dir /s &
    md bin\plugins\ &
    echo "Copying ffmpeg plugin" &
    call curl.exe -o bin\plugins\ffmpeg-3.2.4-win64-static.zip "http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.2.4-win64-static.zip" &
    call 7z.exe x bin\plugins\ffmpeg-3.2.4-win64-static.zip -o"bin\plugins" &
    echo "move ffmpeg.exe and delete ffmpeg leftovers" &
    del bin\plugins\ffmpeg-3.2.4-win64-static.zip &
    move bin\plugins\ffmpeg-3.2.4-win64-static\bin\ffmpeg.exe bin\plugins &
    rmdir /q /s bin\plugins\ffmpeg-3.2.4-win64-static &
    echo "copying qt libraries" &
    windeployqt bin\Pencil2D.exe &
    echo "zipping" &
    Rename bin Pencil2D &
    call 7z.exe a "pencil2d-win64-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" Pencil2D\ &
    echo "zipping done" &
    echo "what's inside?" &
    call 7z.exe l "pencil2d-win64-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    if %upload%==yes (
    echo "deploying to google drive" &
    cd %APPVEYOR_BUILD_FOLDER%\util &
    call %PYTHON%\\python.exe nightly-build-upload.py "%WIN64_NIGHTLY_PARENT%" "%APPVEYOR_BUILD_FOLDER%\build\pencil2d-win64-%date:~-4,4%"-"%date:~-10,2%"-"%date:~7,2%.zip" &
    echo "64 Bit Deployed" ) )
